#!/bin/sh
# worklog:post-pull-hook:v1
# Wrapper that delegates to central Worklog post-pull script (committed hooks).
exec "/home/rogardle/projects/OpenTTD-Migration/.githooks/worklog-post-pull" "$@"
